{
   "config_path": "pipelines/FinaBP17.json", 
   "description": "Add some custom description for this pipeline!", 
   "id": "4", 
   "name": "FinaBP17", 
   "notebooks": [
      {
         "is_clone": "no", 
         "kernel_type": "py3-env", 
         "name": "EventAnalyzerFINA", 
         "path": "ipython/EventAnalyzerFINA.ipynb", 
         "pipeline_status": "on", 
         "type": "Analyzer"
      }
   ], 
   "reports": [
      {
         "date": "2017-08-07", 
         "id": "failures_2017-08-07", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-08-04", 
         "id": "failures_2017-08-04", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-08-03", 
         "id": "failures_2017-08-03", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-08-02", 
         "id": "failures_2017-08-02", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-08-01", 
         "id": "failures_2017-08-01", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-31", 
         "id": "failures_2017-07-31", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-27", 
         "id": "failures_2017-07-27", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-25", 
         "id": "failures_2017-07-25", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-24", 
         "id": "failures_2017-07-24", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-21", 
         "id": "failures_2017-07-21", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-20", 
         "id": "failures_2017-07-20", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-19", 
         "id": "failures_2017-07-19", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))\n\nEzut\u00e1n csak az eng \u00e9s a budapest lett \u00fajraind\u00edtva.", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-17", 
         "id": "failures_2017-07-17", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-14", 
         "id": "failures_2017-07-14", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-13", 
         "id": "failures_2017-07-13", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-12", 
         "id": "failures_2017-07-12", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))\n\nMost csak eng \u00e9s budapest halt meg.", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-11", 
         "id": "failures_2017-07-11", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-10", 
         "id": "failures_2017-07-10", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-05", 
         "id": "failures_2017-07-05", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-04", 
         "id": "failures_2017-07-04", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "twython.exceptions.TwythonError: ('Connection aborted.', OSError(\"(104, 'ECONNRESET')\",))", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }, 
      {
         "date": "2017-07-03", 
         "id": "failures_2017-07-03", 
         "kernel_status": "active", 
         "name": "failures", 
         "note": "", 
         "save_for_remote": "active", 
         "type": "local", 
         "user": "pillere"
      }
   ]
}